### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by gerbyzation** [xhtml2pdf/xhtml2pdf#265]
Hi,

We are working on a Django project that uses django-easy-pdf - which in turns uses xhtml2pdf - to render a pdf. It has been working great untill it recently broke. Looking at the traceback I believe the error is in xhtml2pdf and not easy_pdf. 

To be more specific I suspect commit 8637f24 has broken it. I'm getting `AttributeError: 'bytes' object has no attribute 'encode'` with the traceback found below. 

I'm not very familiar with working on the level of byte-objects, so I'm not entirely sure how this is all supposed to work. Simply commenting out line 182 `data = data.encode("utf-8")` does remove the issue and renders a PDF again. Is this removing something like a safeguard or has this encode call become redundant?

Thanks!

```
Environment:


Request Method: GET
Request URL: http://localhost:8080/accounts/invoice/hq5t6n

Django Version: 1.9
Python Version: 3.4.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'material',
 'opbeat.contrib.django',
 'accounts',
 'games',
 'subscriptions',
 'debug_toolbar',
 'django_extensions')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'opbeat.contrib.django.middleware.OpbeatAPMMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'material.frontend.middleware.SmoothNavigationMiddleware',
 'material.frontend.middleware.UnpjaxMiddleware')



Traceback:

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/playerxp/playerxp/apps/common/decorators.py" in new_view_func
  14.             return view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/views.py" in get
  81.         return self.render_to_response(context)

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/views.py" in render_to_response
  63.         return self.get_pdf_response(context, **response_kwargs)

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/views.py" in get_pdf_response
  59.             **self.get_pdf_kwargs()

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/rendering.py" in render_to_pdf_response
  166.         pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/rendering.py" in render_to_pdf
  139.     return html_to_pdf(content, encoding, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/easy_pdf/rendering.py" in html_to_pdf
  65.                             link_callback=link_callback, **kwargs)

File "/usr/local/lib/python3.4/dist-packages/xhtml2pdf/document.py" in pisaDocument
  182.         data = data.encode("utf-8")

Exception Type: AttributeError at /accounts/invoice/hq5t6n
Exception Value: 'bytes' object has no attribute 'encode'
```

**Comment by benjaoming** [comment]
It seems you're using Python 3, which isn't really supported.

But there is a PR #260  with a couple of TODOs, could you take a look at this and possibly help out make the last pieces of the puzzle fit?

**Comment by gerbyzation** [comment]
I'd be happy to have a look, but I'm not that experienced so I'm not sure if can really help.

**Comment by benjaoming** [comment]
Just a report-back if you can test to see that #260 solves the above-mentioned issue is cool and helps the project progress.

**Comment by gerbyzation** [comment]
Sure, seems to work fine for me!

**Comment by benjaoming** [comment]
Awesome, then I'm closing this issue as fixed by #260 which is gonna get merged and released sooner or later!

**Comment by citizen-stig** [comment]
I still have this issue. I use python 3 and latest develop branch.
I use Flask and here is a part of my code, 
```
source_html = render_template('customer_portal/invoice_pdf.html',
                                  invoice=invoice)
pisa_context = pisa.CreatePDF(source_html)
response = make_response(pisa_context.dest.getvalue())
```
And it fails in ```pisa.CreatePDF```:
````
File "/vagrant/customer_portal/controllers.py", line 139, in invoice_pdf
    pisa_context = pisa.CreatePDF(source_html)
File "/usr/local/lib/python3.4/dist-packages/xhtml2pdf/document.py", line 182, in pisaDocument
    data = data.encode("utf-8")
```

I've debugged a little bit and it looks like a ```data``` and ```out``` are bytes as well, so they don't need to be encoded.

**Comment by citizen-stig** [comment]
I have found a **super-ugly** workaround:
```
class MyBytesIO(object):

    def __init__(self):
        self.storage = BytesIO()

    def write(self, data):
        self.storage.write(data)

    def getvalue(self):
        return self.storage.getvalue()

pdf = MyBytesIO()
pisa_context = pisa.CreatePDF(source_html, dest=pdf)
response = make_response(pisa_context.dest.getvalue())
```

I could propose a simple pull-request, where lines 181-182 will be removed, it should solve the problem.

**Comment by benjaoming** [comment]
Closed by #280, available in 0.1a2
